### PR TITLE
Site Blog dashlet upgraded to Alfresco 5.x version

### PR DESCRIPTION
**Pull request by muralidharand**
The existing site blog dashlet is upgraded against for Alfresco 5.x version, as it was not throwing errors in Alfresco 5.0 version.
To fix this issue, I've upgraded Site Blog Dashlet for Alfresco 5.x version.
It would be great, if you merge this, with the existing Site Blog Dashlet code.

Thanks,
Murali

### CODE REVIEW

**Comment by wabson** [comment]
Hi, thanks for taking the time to put this PR together.

I've not tested the existing add-on on 5.0 but can you explain what exactly the problems were on that version?

In particular I see there are quite a few code changes here, which fit with the new recommended way of instantiating widgets on 5.0. But I'm interested to know did you find that the old code simply did not work (if not how?), or were you just trying to stick to the latest best practice?

In general the aim of the add-ons on Share Extras is to not break backwards compatibility with previous versions of Share, so I'm interested if you did any testing to make sure that these changes also work on 4.x?

Lastly one thing that would be easy to fix - you have included some changes to the README in this PR which is specific to your fork, which I don't think should be part of the PR. Are you able to remove those changes?

**Comment by muralidharand** [comment]
Hi,
Thanks for your response.

* Yes, it is not working in 5.0 and the following resources are giving 404 error, so we're unable to create blog post by using (+) icon.
http://localhost:9090/share/res//share/modules/taglibrary/taglibrary.css 
http://localhost:9090/share/modules/editors/tiny_mce/tiny_mce.js 
http://localhost:9090/share/res//share/modules/simple-dialog.js 
http://localhost:9090/share/res//share/modules/editors/tiny_mce.js 
http://localhost:9090/share/res//share/modules/taglibrary/taglibrary.js 

* I would like to use 5.0 practice also.

I will do the following things:
* Updating the Readme contents 
* Testing the new code with 4.0 instance also.

**Comment by Markus-P** [comment]
Will this also work with Alfresco 4.2.4 EE (and fixes the dashlet bug, so we can create posts from the dashlet again)?

**Comment by wabson** [comment]
The issues on 5.x should now be resolved by #5

**Pull request closed without merging**
